

/* Create Tables */

CREATE TABLE USER
(
	ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
	NAME VARCHAR(128) NOT NULL COMMENT 'name',
	AGE INT UNSIGNED NOT NULL COMMENT 'age',
	SEX ENUM(MALE,FEMALE,OTHER) NOT NULL COMMENT 'sex',
	PRIMARY KEY (ID)
) COMMENT = 'user';


CREATE TABLE WITHDRAW
(
	ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
	USER_ID BIGINT UNSIGNED NOT NULL COMMENT 'user_id',
	AMOUNT INT NOT NULL COMMENT 'amount',
	STATUS ENUM('PENDING','ACCEPTED') NOT NULL COMMENT 'status',
	ENTRY_DATETIME TIMESTAMP NOT NULL COMMENT 'entry_datetime',
	PRIMARY KEY (ID)
) COMMENT = 'withdraw';



/* Create Indexes */

CREATE INDEX IX_USER_AGE_SEX USING BTREE ON USER (SEX ASC, AGE ASC);



/* Create Foreign Keys */

ALTER TABLE WITHDRAW
	ADD CONSTRAINT FK_WITHDRAW_USER FOREIGN KEY (USER_ID)
	REFERENCES USER (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



